### ISSUE TITLE
Convert Fisheye footage to sphere

### ISSUE THREAD

**Issue by sonia-ch** [elBjarnacho/BikingThroughStockholm#1]
Use FFMPEG remap filter to map the fisheye video to sphere, so that it can be viewed at 360º player

**Comment by elBjarnacho** [comment]
We managed to manually remap the videos that have lower resolution. However we also noticed that this is something that Unity does automatically for you when you use your video as a panoramic skybox 😅 So probably we will let Unity take care of this for us in the future 💥
